# Generated by Codex on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPrint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpn',
            name='full_lpn',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
