# Generated by Codex on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPrint', '0003_printjob_lpn_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='browser_language',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='printjob',
            name='browser_platform',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='printjob',
            name='browser_vendor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='printjob',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='requested_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='printjob',
            name='sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='printjob',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('sent', 'Sent'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='reserved', max_length=20),
        ),
    ]
