# Generated by Codex on 2026-04-28

from django.db import migrations, models


def populate_existing_suffixes(apps, schema_editor):
    LPN = apps.get_model('userPrint', 'LPN')
    LPNSuffix = apps.get_model('userPrint', 'LPNSuffix')

    suffixes = set()
    for full_lpn in LPN.objects.values_list('full_lpn', flat=True).iterator(chunk_size=2000):
        if full_lpn:
            suffixes.add(full_lpn[-6:])

    LPNSuffix.objects.bulk_create(
        [LPNSuffix(suffix=suffix) for suffix in suffixes],
        batch_size=2000,
        ignore_conflicts=True,
    )


def clear_suffixes(apps, schema_editor):
    LPNSuffix = apps.get_model('userPrint', 'LPNSuffix')
    LPNSuffix.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('userPrint', '0004_printjob_audit_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LPNSuffix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix', models.CharField(db_index=True, max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(populate_existing_suffixes, clear_suffixes),
    ]
